apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ecomm-api
  namespace: westbay-ecommerce
  labels:
    app: ecomm-api
    app.kubernetes.io/name: ecomm-api
    app.kubernetes.io/part-of: westbay-ecommerce
spec:
  secretName: ecomm-api-tls
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - westbay-ecommerce-api.k3s.l01.ukad.dev
