apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecomm-api-data
  namespace: westbay-ecommerce
  labels:
    app: ecomm-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecomm-api-uploads
  namespace: westbay-ecommerce
  labels:
    app: ecomm-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
