openapi: 3.0.3
info:
  title: Authentication API
  description: |
    Role-based access control API for eCommerce SaaS backoffice.

    **MVP Implementation**: Hardcoded profiles with simulated login (no passwords).
    **Future Production**: Real authentication with OAuth2/OIDC.
  version: 1.0.0
  contact:
    name: eCommerce SaaS Team

servers:
  - url: http://localhost:3000/api/v1
    description: Development server

tags:
  - name: Authentication
    description: Login, logout, session management

paths:
  /auth/login:
    post:
      tags: [Authentication]
      summary: Authenticate user with profile selection
      description: |
        **MVP**: Select hardcoded profile and optional tenant.
        **Future**: Accept credentials and return JWT token.
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [profileId]
              properties:
                profileId:
                  type: string
                  description: ID of the hardcoded profile
                  example: "tenant-admin-1"
                tenantId:
                  type: string
                  description: Selected tenant ID (required for non-superadmin roles)
                  example: "tenant-a"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid request (missing tenant for scoped role)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication failed (invalid profile)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      tags: [Authentication]
      summary: End current session
      description: Clears authentication state and invalidates session.
      operationId: logout
      responses:
        '204':
          description: Logout successful (no content)
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/session:
    get:
      tags: [Authentication]
      summary: Get current session
      description: Returns current authenticated session or null if not authenticated.
      operationId: getSession
      responses:
        '200':
          description: Session retrieved
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/UserSession'
                  - type: object
                    properties:
                      session:
                        type: null
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/tenants:
    get:
      tags: [Authentication]
      summary: Get available tenants for tenant selector
      description: Returns list of tenants that user can select during login.
      operationId: getTenants
      responses:
        '200':
          description: Tenants retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenants:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tenant'

  /auth/profiles:
    get:
      tags: [Authentication]
      summary: Get available hardcoded profiles (MVP only)
      description: |
        **MVP ONLY**: Returns list of hardcoded profiles for login screen.
        **Production**: This endpoint will not exist; users will enter credentials.
      operationId: getProfiles
      responses:
        '200':
          description: Profiles retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  profiles:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserProfile'

components:
  schemas:
    UserProfile:
      type: object
      required: [id, displayName, email, role]
      properties:
        id:
          type: string
          example: "tenant-admin-1"
        displayName:
          type: string
          example: "Tenant Admin (Demo Store)"
        email:
          type: string
          format: email
          example: "admin@tenant-a.local"
        role:
          $ref: '#/components/schemas/Role'
        defaultTenantId:
          type: string
          nullable: true
          example: "tenant-a"

    Role:
      type: string
      enum: [SUPERADMIN, TENANT_ADMIN, TENANT_USER]
      description: |
        - SUPERADMIN: Full platform access, manages all tenants
        - TENANT_ADMIN: Full access within selected tenant
        - TENANT_USER: View-all, edit products/categories only within selected tenant

    UserSession:
      type: object
      required: [profile, authenticatedAt]
      properties:
        profile:
          $ref: '#/components/schemas/UserProfile'
        selectedTenantId:
          type: string
          nullable: true
          description: Currently active tenant (required for non-superadmin)
          example: "tenant-a"
        authenticatedAt:
          type: string
          format: date-time
          example: "2025-10-24T10:30:00Z"
        expiresAt:
          type: string
          format: date-time
          nullable: true
          description: Session expiry (null = never expires in MVP)
          example: null

    Tenant:
      type: object
      required: [id, name, displayName]
      properties:
        id:
          type: string
          example: "tenant-a"
        name:
          type: string
          description: Internal name
          example: "tenant-a"
        displayName:
          type: string
          description: Human-readable name for UI
          example: "Demo Store"

    LoginResponse:
      type: object
      required: [session]
      properties:
        session:
          $ref: '#/components/schemas/UserSession'
        token:
          type: string
          nullable: true
          description: JWT token (future production feature)
          example: null

    Error:
      type: object
      required: [error, message]
      properties:
        error:
          type: string
          example: "AUTHENTICATION_FAILED"
        message:
          type: string
          example: "Invalid profile ID"
        statusCode:
          type: integer
          example: 401
