apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ecomm-frontend
  namespace: westbay-ecommerce
  labels:
    app: ecomm-frontend
    app.kubernetes.io/name: ecomm-frontend
    app.kubernetes.io/part-of: westbay-ecommerce
spec:
  secretName: ecomm-frontend-tls
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - westbay-ecommerce.k3s.l01.ukad.dev
